# Generated by Django 3.0.3 on 2020-03-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodSafeNews', '0003_auto_20200301_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodsafe_news',
            options={'ordering': ['news_time']},
        ),
        migrations.AlterField(
            model_name='foodsafe_news',
            name='news_name',
            field=models.CharField(max_length=50),
        ),
    ]
