# Generated by Django 3.0.3 on 2020-03-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodSafeBlacklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsafe_blacklist',
            name='criminal_behavior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodsafe_blacklist',
            name='punishment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
